#!/bin/bash

d=`date +%Y%m%d-%H:%M` #variable with my date formate#
cd /media/usb/backup/ #way of the hardisk#

#Function which allows to delete the oldest file which is in the first line#
delete_old()
{
if [ `ls | wc -l` -gt 7 ]; then


rm $(ls | head -n 1)

fi
}
#Function which allows to protect it .tar in my hard disk#
save_conf_html()
{
if [ -e /var/www/html ]; then

tar -cvzf /media/usb/backup/backup$d".tar.gz" /var/www/html
fi

}
save_conf_html
delete_old

crontab -e
0 3 * * 1 /home/pi/sauvegarde2.sh

